# -*- coding: utf-8 -*-
"""Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOGfL8kxuqdtTZmpKZ_iuNzRgS5qkGv9
"""



import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn import tree
import pickle
import joblib

Heart=pd.read_csv("E:\project ML\Heart.csv")
Heart

le=LabelEncoder()
le=le.fit(Heart.Sex)
Heart['Sex']=le.transform(Heart.Sex)

le=le.fit(Heart.ChestPainType)
Heart['ChestPainType']=le.transform(Heart.ChestPainType)

le=le.fit(Heart.RestingECG)
Heart['RestingECG']=le.transform(Heart.RestingECG)

le=le.fit(Heart.ExerciseAngina)
Heart['ExerciseAngina']=le.transform(Heart.ExerciseAngina)

le=le.fit(Heart.ST_Slope)
Heart['ST_Slope']=le.transform(Heart.ST_Slope)

Heart



#from sklearn.model_selection import train_test_split
predictors = Heart.drop("HeartDisease",axis=1)
HeartDisease = Heart["HeartDisease"]
X_train,X_test,Y_train,Y_test =train_test_split(predictors,HeartDisease,test_size=0.33,random_state=0)

"""# Model Fitting

Decision Tree Algorithm
"""

Tree=DecisionTreeClassifier(criterion='entropy',random_state=0,max_depth=4)
#lets predict it
Tree.fit(X_train,Y_train)

y_pred=Tree.predict(X_test)
#from sklearn import metrics
#import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ",metrics.accuracy_score(Y_test,y_pred))

filename = "Tree_model.sav"
pickle.dump(Tree,open(filename,'wb'))

#loading model
load_model = pickle.load(open("Tree_model.sav",'rb'))

input_data = [40,1,1,140,289,0,1,172,0,0.2,2]

#changing input data to numpy array
input_data_as_array = np.asarray(input_data)

#reshape array
input_data_reshape = input_data_as_array.reshape(1,-1)

prediction = load_model.predict(input_data_reshape)
print(prediction)

if (prediction[0] == 0):
    print('The person is does not have heart diisease')
else:
    print('The person have heart diisease')